### ISSUE TITLE
Error:Unable to find method 

### ISSUE THREAD

**Issue by armoun** [klinker24/slideover-messaging#1]
`Error:Unable to find method 'org.gradle.api.artifacts.Configuration.setExtendsFrom(Ljava/lang/Iterable;)Lorg/gradle/api/artifacts/Configuration;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.`

**Comment by klinker24** [comment]
I probably need to bring in all the latest dependencies on this project. I will look at it later today.

**Comment by armoun** [comment]
@klinker24 thanks , this error solved by update gradle , after this error i see this error
`Gradle icon error, Manifest Merger` but i fixed that by add this in manifest application element 
" tools:replace="android:icon" ", and i know see this error 
`Error:(247, 25) error: cannot find symbol method setLatestEventInfo(SlideOverService,String,String,PendingIntent)`
